### ISSUE TITLE
All the crc values can be stored in a int type then put into ByteBuf

### ISSUE THREAD

**Issue by everwanna** [AgoraIO/AgoraDynamicKey#22]
https://github.com/AgoraIO/AgoraDynamicKey/blob/9dbcbdd13300c1470973a20707017b66b2700b79/java/src/io/agora/media/AccessToken.java#L167

It's not necessary to convert the crc value into bytes before putting into ByteBuf.

**Comment by cmder** [comment]
This is to circumvent the differences in data type definitions between C ++ and the Java language by converting string operations to byte operations.

**Comment by everwanna** [comment]
Please check this code in ByteBuf
```
    // packUint32
    public ByteBuf put(int v) {
        buffer.putInt(v);
        return this;
    }
```

**Comment by everwanna** [comment]
fixed in https://github.com/AgoraIO/AgoraDynamicKey/commit/be33d6ad33d4285450b60026307ad804b65798dd
